- name: Install Drupal on EC2
  hosts: webservers
  become: yes
  vars:
    # Database connection settings
    drupal_db_host: "terraform-20250328144237841600000005.cdk00qyiacy0.us-east-1.rds.amazonaws.com"
    drupal_db_port: "3306"
    drupal_db_name: "drupal_db"
    drupal_db_user: "drupal_user"
    drupal_db_password: "drupaldb123!" 

  tasks:
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required PHP packages
      apt:
        name:
          - php
          - php-cli
          - php-fpm
          - php-json
          - php-common
          - php-mysql
          - php-zip
          - php-gd
          - php-intl
          - php-mbstring
          - php-curl
          - php-xml
          - php-pear
          - php-tidy
          - php-soap
          - php-bcmath
          - php-xmlrpc
        state: present

    - name: Download Drupal tarball
      get_url:
        url: https://www.drupal.org/download-latest/tar.gz
        dest: /tmp/drupal.tar.gz

    - name: Extract Drupal
      unarchive:
        src: /tmp/drupal.tar.gz
        dest: /var/www/html/
        remote_src: yes
        extra_opts:
          - --strip-components=1  # This removes the top-level folder in the extracted tarball

    - name: List extracted files in /var/www/html/
      command: ls -l /var/www/html/
      register: extracted_files

    - debug:
        var: extracted_files.stdout_lines

    - name: Find extracted Drupal folder
      command: find /var/www/html/ -maxdepth 1 -type d -name "drupal*"
      register: drupal_folder

    - name: Debug extracted Drupal folder
      debug:
        var: drupal_folder.stdout

    - name: Check if Drupal directory exists
      stat:
        path: /var/www/html/drupal
      register: drupal_dir_stat

    - name: Move extracted Drupal to /var/www/html/drupal
      command: mv "{{ drupal_folder.stdout }}" /var/www/html/drupal
      when: drupal_folder.stdout != "" and drupal_dir_stat.stat.exists == false

    - name: Set correct ownership and permissions
      file:
        path: /var/www/html/drupal
        owner: www-data
        group: www-data
        mode: "0755"
        recurse: yes

    - name: Create Apache VirtualHost for Drupal
      template:
        src: drupal.conf.j2
        dest: /etc/apache2/sites-available/drupal.conf
      vars:
        ip_address: "{{ ansible_host }}"

    - name: Update the VirtualHost configuration for correct DocumentRoot
      replace:
        path: /etc/apache2/sites-available/drupal.conf
        regexp: '^DocumentRoot /var/www/html/drupal$'
        replace: 'DocumentRoot /var/www/html/drupal/drupal-11.1.5'

    - name: Update the Directory block in the configuration
      replace:
        path: /etc/apache2/sites-available/drupal.conf
        regexp: '<Directory /var/www/html/drupal>'
        replace: '<Directory /var/www/html/drupal/drupal-11.1.5>'

    - name: Check Apache configuration
      command: apachectl -t

    - name: Enable Apache rewrite module
      command: a2enmod rewrite

    - name: Enable Drupal site
      command: a2ensite drupal.conf

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

    - name: Configure database settings for Drupal
      template:
        src: settings.php.j2
        dest: /var/www/html/drupal/sites/default/settings.php
      vars:
        drupal_db_host: "{{ drupal_db_host }}"
        drupal_db_port: "{{ drupal_db_port }}"
        drupal_db_name: "{{ drupal_db_name }}"
        drupal_db_user: "{{ drupal_db_user }}"
        drupal_db_password: "{{ drupal_db_password }}"

    - name: Set permissions on settings.php
      file:
        path: /var/www/html/drupal/sites/default/settings.php
        owner: www-data
        group: www-data
        mode: '0644'
